#!/bin/sh

set_wallpaper &
dwm_bar &
xcompmgr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst &
xset r rate 300 50 &
sxhkd &
unclutter &
~/.config/mouse.sh &

exec dwm > /dev/null 2>&1
